name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git log to get SOURCE_DATE_EPOCH

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Keystore
        if: env.KEYSTORE_FILE != null
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: |
          mkdir -p /home/runner/keystore
          echo "$KEYSTORE_FILE" | base64 -d > /home/runner/keystore/metapurge.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Reproducible Release APK
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          export SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)
          ./gradlew assembleRelease --no-build-cache --no-daemon

      - name: Rename and Upload APK
        run: |
          mv app/build/outputs/apk/release/app-release.apk MetaPurge-1.0.apk
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MetaPurge-APK
          path: MetaPurge-1.0.apk
